// constants/formOptions.ts
export const FORM_OPTIONS = {
    nationalities: [
        {label: "Afghane", country_name: "Afghanistan", country_code: "af"},
        {label: "Albanaise", country_name: "Albania", country_code: "al"},
        {label: "Algérienne", country_name: "Algeria", country_code: "dz"},
        {label: "Allemande", country_name: "Germany", country_code: "de"},
        {label: "Américaine", country_name: "United States", country_code: "us"},
        {label: "Andorrane", country_name: "Andorra", country_code: "ad"},
        {label: "Angolaise", country_name: "Angola", country_code: "ao"},
        {label: "Argentine", country_name: "Argentina", country_code: "ar"},
        {label: "Arménienne", country_name: "Armenia", country_code: "am"},
        {label: "Australienne", country_name: "Australia", country_code: "au"},
        {label: "Autrichienne", country_name: "Austria", country_code: "at"},
        {label: "Belge", country_name: "Belgium", country_code: "be"},
        {label: "Brésilienne", country_name: "Brazil", country_code: "br"},
        {label: "Britannique", country_name: "United Kingdom", country_code: "gb"},
        {label: "Canadienne", country_name: "Canada", country_code: "ca"},
        {label: "Chilienne", country_name: "Chile", country_code: "cl"},
        {label: "Chinoise", country_name: "China", country_code: "cn"},
        {label: "Colombienne", country_name: "Colombia", country_code: "co"},
        {label: "Coréenne", country_name: "South Korea", country_code: "kr"},
        {label: "Croate", country_name: "Croatia", country_code: "hr"},
        {label: "Danoise", country_name: "Denmark", country_code: "dk"},
        {label: "Égyptienne", country_name: "Egypt", country_code: "eg"},
        {label: "Espagnole", country_name: "Spain", country_code: "es"},
        {label: "Estonienne", country_name: "Estonia", country_code: "ee"},
        {label: "Finlandaise", country_name: "Finland", country_code: "fi"},
        {label: "Française", country_name: "France", country_code: "fr"},
        {label: "Grecque", country_name: "Greece", country_code: "gr"},
        {label: "Hongroise", country_name: "Hungary", country_code: "hu"},
        {label: "Indienne", country_name: "India", country_code: "in"},
        {label: "Indonésienne", country_name: "Indonesia", country_code: "id"},
        {label: "Irlandaise", country_name: "Ireland", country_code: "ie"},
        {label: "Israélienne", country_name: "Israel", country_code: "il"},
        {label: "Italienne", country_name: "Italy", country_code: "it"},
        {label: "Japonaise", country_name: "Japan", country_code: "jp"},
        {label: "Libanaise", country_name: "Lebanon", country_code: "lb"},
        {label: "Luxembourgeoise", country_name: "Luxembourg", country_code: "lu"},
        {label: "Marocaine", country_name: "Morocco", country_code: "ma"},
        {label: "Mexicaine", country_name: "Mexico", country_code: "mx"},
        {label: "Monégasque", country_name: "Monaco", country_code: "mc"},
        {label: "Néerlandaise", country_name: "Netherlands", country_code: "nl"},
        {label: "Nigériane", country_name: "Nigeria", country_code: "ng"},
        {label: "Norvégienne", country_name: "Norway", country_code: "no"},
        {label: "Néo-zélandaise", country_name: "New Zealand", country_code: "nz"},
        {label: "Pakistanaise", country_name: "Pakistan", country_code: "pk"},
        {label: "Palestinienne", country_name: "Palestine", country_code: "ps"},
        {label: "Polonaise", country_name: "Poland", country_code: "pl"},
        {label: "Portugaise", country_name: "Portugal", country_code: "pt"},
        {label: "Qatarienne", country_name: "Qatar", country_code: "qa"},
        {label: "Roumaine", country_name: "Romania", country_code: "ro"},
        {label: "Russe", country_name: "Russia", country_code: "ru"},
        {label: "Saoudienne", country_name: "Saudi Arabia", country_code: "sa"},
        {label: "Sénégalaise", country_name: "Senegal", country_code: "sn"},
        {label: "Serbe", country_name: "Serbia", country_code: "rs"},
        {label: "Singapourienne", country_name: "Singapore", country_code: "sg"},
        {label: "Slovaque", country_name: "Slovakia", country_code: "sk"},
        {label: "Slovène", country_name: "Slovenia", country_code: "si"},
        {label: "Suédoise", country_name: "Sweden", country_code: "se"},
        {label: "Suisse", country_name: "Switzerland", country_code: "ch"},
        {label: "Syrienne", country_name: "Syria", country_code: "sy"},
        {label: "Tchèque", country_name: "Czech Republic", country_code: "cz"},
        {label: "Tunisienne", country_name: "Tunisia", country_code: "tn"},
        {label: "Turque", country_name: "Turkey", country_code: "tr"},
        {label: "Ukrainienne", country_name: "Ukraine", country_code: "ua"},
        {label: "Vénézuélienne", country_name: "Venezuela", country_code: "ve"},
        {label: "Vietnamienne", country_name: "Vietnam", country_code: "vn"}
    ],

    countries: [
        {label: "Afghanistan", country_name: "Afghanistan", country_code: "af"},
        {label: "Albanie", country_name: "Albania", country_code: "al"},
        {label: "Algérie", country_name: "Algeria", country_code: "dz"},
        {label: "Allemagne", country_name: "Germany", country_code: "de"},
        {label: "États-Unis", country_name: "United States", country_code: "us"},
        {label: "Andorre", country_name: "Andorra", country_code: "ad"},
        {label: "Angola", country_name: "Angola", country_code: "ao"},
        {label: "Argentine", country_name: "Argentina", country_code: "ar"},
        {label: "Arménie", country_name: "Armenia", country_code: "am"},
        {label: "Australie", country_name: "Australia", country_code: "au"},
        {label: "Autriche", country_name: "Austria", country_code: "at"},
        {label: "Belgique", country_name: "Belgium", country_code: "be"},
        {label: "Brésil", country_name: "Brazil", country_code: "br"},
        {label: "Royaume-Uni", country_name: "United Kingdom", country_code: "gb"},
        {label: "Canada", country_name: "Canada", country_code: "ca"},
        {label: "Chili", country_name: "Chile", country_code: "cl"},
        {label: "Chine", country_name: "China", country_code: "cn"},
        {label: "Colombie", country_name: "Colombia", country_code: "co"},
        {label: "Corée du Sud", country_name: "South Korea", country_code: "kr"},
        {label: "Croatie", country_name: "Croatia", country_code: "hr"},
        {label: "Danemark", country_name: "Denmark", country_code: "dk"},
        {label: "Égypte", country_name: "Egypt", country_code: "eg"},
        {label: "Espagne", country_name: "Spain", country_code: "es"},
        {label: "Estonie", country_name: "Estonia", country_code: "ee"},
        {label: "Finlande", country_name: "Finland", country_code: "fi"},
        {label: "France", country_name: "France", country_code: "fr"},
        {label: "Grèce", country_name: "Greece", country_code: "gr"},
        {label: "Hongrie", country_name: "Hungary", country_code: "hu"},
        {label: "Inde", country_name: "India", country_code: "in"},
        {label: "Indonésie", country_name: "Indonesia", country_code: "id"},
        {label: "Irlande", country_name: "Ireland", country_code: "ie"},
        {label: "Israël", country_name: "Israel", country_code: "il"},
        {label: "Italie", country_name: "Italy", country_code: "it"},
        {label: "Japon", country_name: "Japan", country_code: "jp"},
        {label: "Liban", country_name: "Lebanon", country_code: "lb"},
        {label: "Luxembourg", country_name: "Luxembourg", country_code: "lu"},
        {label: "Maroc", country_name: "Morocco", country_code: "ma"},
        {label: "Mexique", country_name: "Mexico", country_code: "mx"},
        {label: "Monaco", country_name: "Monaco", country_code: "mc"},
        {label: "Pays-Bas", country_name: "Netherlands", country_code: "nl"},
        {label: "Nigeria", country_name: "Nigeria", country_code: "ng"},
        {label: "Norvège", country_name: "Norway", country_code: "no"},
        {label: "Nouvelle-Zélande", country_name: "New Zealand", country_code: "nz"},
        {label: "Pakistan", country_name: "Pakistan", country_code: "pk"},
        {label: "Palestine", country_name: "Palestine", country_code: "ps"},
        {label: "Pologne", country_name: "Poland", country_code: "pl"},
        {label: "Portugal", country_name: "Portugal", country_code: "pt"},
        {label: "Qatar", country_name: "Qatar", country_code: "qa"},
        {label: "Roumanie", country_name: "Romania", country_code: "ro"},
        {label: "Russie", country_name: "Russia", country_code: "ru"},
        {label: "Singapour", country_name: "Singapore", country_code: "sg"},
        {label: "Suède", country_name: "Sweden", country_code: "se"},
        {label: "Suisse", country_name: "Switzerland", country_code: "ch"},
        {label: "Thaïlande", country_name: "Thailand", country_code: "th"},
        {label: "Turquie", country_name: "Turkey", country_code: "tr"},
        {label: "Ukraine", country_name: "Ukraine", country_code: "ua"},
        {label: "République tchèque", country_name: "Czech Republic", country_code: "cz"},
    ],

    responseFormats: [
        {value: "", label: "Sélectionner un format..."},
        {value: "zip", label: "ZIP"},
        {value: "rar", label: "RAR"},
        {value: "html", label: "HTML"},
        {value: "excel", label: "Excel"},
        {value: "csv", label: "CSV"},
        {value: "word", label: "Word"},
        {value: "pdf", label: "PDF"},
        {value: "txt", label: "TXT"},
        {value: "Autre", label: "Autre"}
    ],

    requiredDocuments: [
        {value: "", label: "Sélectionner un document..."},
        {value: "Carte d'identité", label: "Carte d'identité"},
        {value: "Passeport", label: "Passeport"},
        {value: "Justificatif de domicile", label: "Justificatif de domicile"},
        {value: "Autre", label: "Autre"}
    ],

    easyAccessLevels: [
        {value: "1", note: "1", explanation: "Carte d'identité + preuve d'identité par envoi postal (très restrictif)"},
        {value: "2", note: "2", explanation: "Carte d'identité obligatoire, envoi numérique ou formulaire complexe"},
        {value: "3", note: "3", explanation: "Preuve d'identité par email, procédure modérée"},
        {value: "3,5", note: "3,5", explanation: "Export intégré dans le compte mais pas simple à trouver"},
        {value: "4", note: "4", explanation: "Export possible par email, procédure simple"},
        {value: "5", note: "5", explanation: "Export intégré dans le compte, accessible en un clic, clairement affiché"}
    ],

    responseDelays: [
        {value: "", label: "Sélectionner un délai..."},
        {value: "1 mois conformément au RGPD", label: "1 mois conformément au RGPD"},
        {value: "Réponse automatique", label: "Réponse automatique"},
        {value: "Plus d'un mois", label: "Plus d'un mois"},
        {value: "Autre", label: "Autre"}
    ]
};
